//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LonestarShowdown.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LonestarShowdown.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to add {0} to your team?.
        /// </summary>
        internal static string AddConfirmationMessage {
            get {
                return ResourceManager.GetString("AddConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to approve {0}&apos;s request to join the league with {1}?.
        /// </summary>
        internal static string ApproveTeamConfirmationMessage {
            get {
                return ResourceManager.GetString("ApproveTeamConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texas Soccer Association.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlankProfile {
            get {
                object obj = ResourceManager.GetObject("BlankProfile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlankTeam {
            get {
                object obj = ResourceManager.GetObject("BlankTeam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team request has been successfully submitted to the manager of {0}..
        /// </summary>
        internal static string ChangeTeamRequestedMessage {
            get {
                return ResourceManager.GetString("ChangeTeamRequestedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Required.
        /// </summary>
        internal static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DefaultTeamLogo {
            get {
                object obj = ResourceManager.GetObject("DefaultTeamLogo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete your profile picture?.
        /// </summary>
        internal static string DeletePictureMessage {
            get {
                return ResourceManager.GetString("DeletePictureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this game?.
        /// </summary>
        internal static string DeleteScheduleItemMessage {
            get {
                return ResourceManager.GetString("DeleteScheduleItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete your team?.
        /// </summary>
        internal static string DeleteTeamMessage {
            get {
                return ResourceManager.GetString("DeleteTeamMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email &quot;{0}&quot; is already taken. Please, use a different email..
        /// </summary>
        internal static string EmailExistsMessage {
            get {
                return ResourceManager.GetString("EmailExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account with the email you entered does not exist..
        /// </summary>
        internal static string EmailNotFoundMessage {
            get {
                return ResourceManager.GetString("EmailNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty and has to be at least 8 characters long..
        /// </summary>
        internal static string EmptyPasswordMessage {
            get {
                return ResourceManager.GetString("EmptyPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been an error..
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size cannot not exceed 256 KB..
        /// </summary>
        internal static string FileSizeExceededMessage {
            get {
                return ResourceManager.GetString("FileSizeExceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files (*.png,*.jpg,*.jpeg,*.bmp)|*.png;*.jpg;*.jpeg;*.bmp.
        /// </summary>
        internal static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error with your E-Mail/Password combination. Please, try again..
        /// </summary>
        internal static string InvalidCredentialsMessage {
            get {
                return ResourceManager.GetString("InvalidCredentialsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select home and away team..
        /// </summary>
        internal static string InvalidTeamSelectionMessage {
            get {
                return ResourceManager.GetString("InvalidTeamSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To verify your phone number, enter the last 4 digits including {0}..
        /// </summary>
        internal static string LongPhoneMessage {
            get {
                return ResourceManager.GetString("LongPhoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not currently belong to any team. You are on a free agent list. You can request a specific team..
        /// </summary>
        internal static string NoTeamFreeAgentMessage {
            get {
                return ResourceManager.GetString("NoTeamFreeAgentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not currently belong to any team. You can create a team..
        /// </summary>
        internal static string NoTeamManagerMessage {
            get {
                return ResourceManager.GetString("NoTeamManagerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not currently belong to any team. You have requested to join {0}..
        /// </summary>
        internal static string NoTeamPlayerMessage {
            get {
                return ResourceManager.GetString("NoTeamPlayerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select date and time..
        /// </summary>
        internal static string NullDateTimeMessage {
            get {
                return ResourceManager.GetString("NullDateTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        internal static string PasswordChangeSuccessMessage {
            get {
                return ResourceManager.GetString("PasswordChangeSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your passwords don&apos;t match..
        /// </summary>
        internal static string PasswordsDontMatchMessage {
            get {
                return ResourceManager.GetString("PasswordsDontMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player you are trying to add to your team is already taken. Please, hit refresh your list of available players..
        /// </summary>
        internal static string PlayerAlreadyTaken {
            get {
                return ResourceManager.GetString("PlayerAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password last changed on {0} at {1}..
        /// </summary>
        internal static string PWLastChangedMessage {
            get {
                return ResourceManager.GetString("PWLastChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to reject {0}&apos;s request to join your team?.
        /// </summary>
        internal static string RejectConfirmationMessage {
            get {
                return ResourceManager.GetString("RejectConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to reject {0}&apos;s request to join the league with {1}? (Warning: This will remove the team from the database.).
        /// </summary>
        internal static string RejectTeamConfirmationMessage {
            get {
                return ResourceManager.GetString("RejectTeamConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to remove {0} from your team?.
        /// </summary>
        internal static string RemovePlayerMessage {
            get {
                return ResourceManager.GetString("RemovePlayerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use+{0}+as+your+TSA+account+reset+code..
        /// </summary>
        internal static string ResetTextMessage {
            get {
                return ResourceManager.GetString("ResetTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select two different teams..
        /// </summary>
        internal static string SameTeamSelectionMessage {
            get {
                return ResourceManager.GetString("SameTeamSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If {0} matches the last 4 digits of your phone number, we&apos;ll send you a code..
        /// </summary>
        internal static string SecurityCodeMessage {
            get {
                return ResourceManager.GetString("SecurityCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text ********{0}.
        /// </summary>
        internal static string ShortPhoneMessage {
            get {
                return ResourceManager.GetString("ShortPhoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your security question and/or answer last changed on {0} at {1}..
        /// </summary>
        internal static string SQLastChangedMessage {
            get {
                return ResourceManager.GetString("SQLastChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to suspend {0}?.
        /// </summary>
        internal static string SuspendTeamMessage {
            get {
                return ResourceManager.GetString("SuspendTeamMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team with the following name already exists: {0}. Please, pick a different name..
        /// </summary>
        internal static string TeamExistsMessage {
            get {
                return ResourceManager.GetString("TeamExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to unsuspend {0}?.
        /// </summary>
        internal static string UnsuspendTeamMessage {
            get {
                return ResourceManager.GetString("UnsuspendTeamMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer to the security answer does not match our records..
        /// </summary>
        internal static string WrongAnswerMessage {
            get {
                return ResourceManager.GetString("WrongAnswerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That code didn&apos;t work. Check the code and try again..
        /// </summary>
        internal static string WrongCodeMessage {
            get {
                return ResourceManager.GetString("WrongCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current password is incorrect..
        /// </summary>
        internal static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
